### ISSUE TITLE
大佬你好，感谢你分享的efi，我和你一样同款机子，但是我的是核显，替换完efi选择安装后跑代码，跑完代码就黑屏重启了，是不是要设置一下什么，可以的话能告诉我下吗，谢谢！

### ISSUE THREAD

**Issue by In1Earth** [Road-tech/Hackintosh_LenovoM910X_8100B_RX460_OC#2]

**Comment by Road-tech** [comment]
你需要补充cpu对应的核显的id，和显卡接口的定制。具体可以参考https://blog.daliansky.net/Intel-core-display-platformID-finishing.html
和 https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html

另外建议调试过程用dp接口

**Comment by In1Earth** [comment]
明白了，谢谢大佬的解答。
